// this code is autogenerated, do not check it into to your code repository

// ref lib/roaring.ex:3
/// nif: example_fun/2
fn example_fun(value1: f64, value2: f64) bool {
  return value1 > value2;
}
